export const advancedPaymentProcessor = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_paymentProcessorStorageAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "BuyerCannotBeSeller", type: "error" },
  { inputs: [], name: "DuplicateTask", type: "error" },
  { inputs: [], name: "EmptyMetaInvoice", type: "error" },
  { inputs: [], name: "InsufficientBalance", type: "error" },
  { inputs: [], name: "InvalidDisputeResolution", type: "error" },
  { inputs: [], name: "InvalidInvoiceState", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "sent", type: "uint256" },
      { internalType: "uint256", name: "expected", type: "uint256" },
    ],
    name: "InvalidMetaInvoicePaymentAmount",
    type: "error",
  },
  { inputs: [], name: "InvalidNativePayment", type: "error" },
  { inputs: [], name: "InvalidPrice", type: "error" },
  { inputs: [], name: "InvalidSellersPayoutShare", type: "error" },
  { inputs: [], name: "InvoiceAlreadyExists", type: "error" },
  { inputs: [], name: "InvoiceDoesNotExist", type: "error" },
  { inputs: [], name: "InvoiceExpired", type: "error" },
  { inputs: [], name: "MetaInvoiceAlreadyExists", type: "error" },
  { inputs: [], name: "NotAuthorized", type: "error" },
  { inputs: [], name: "PriceCannotBeZero", type: "error" },
  { inputs: [], name: "PriceIsTooLow", type: "error" },
  { inputs: [], name: "Reentrancy", type: "error" },
  { inputs: [], name: "SequencerDown", type: "error" },
  { inputs: [], name: "StalePrice", type: "error" },
  { inputs: [], name: "StalePriceFeed", type: "error" },
  { inputs: [], name: "TaskNotFound", type: "error" },
  { inputs: [], name: "UnsupportedToken", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
    ],
    name: "DisputeCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
    ],
    name: "DisputeDismissed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
    ],
    name: "DisputeResolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "sellerAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "buyerAmount",
        type: "uint256",
      },
    ],
    name: "DisputeSettled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
      {
        indexed: true,
        internalType: "address",
        name: "escrow",
        type: "address",
      },
    ],
    name: "EscrowCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
    ],
    name: "InvoiceCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
      {
        components: [
          {
            internalType: "uint216",
            name: "invoiceNonce",
            type: "uint216",
          },
          { internalType: "uint40", name: "paidAt", type: "uint40" },
          { internalType: "uint40", name: "createdAt", type: "uint40" },
          { internalType: "uint40", name: "releaseAt", type: "uint40" },
          { internalType: "uint40", name: "expiresAt", type: "uint40" },
          { internalType: "uint8", name: "state", type: "uint8" },
          {
            internalType: "uint32",
            name: "escrowHoldPeriod",
            type: "uint32",
          },
          {
            internalType: "uint216",
            name: "metaInvoiceId",
            type: "uint216",
          },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "address", name: "escrow", type: "address" },
          {
            internalType: "address",
            name: "paymentToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amountPaid",
            type: "uint256",
          },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "balance", type: "uint256" },
        ],
        indexed: false,
        internalType: "struct IAdvancedPaymentProcessor.Invoice",
        name: "invoice",
        type: "tuple",
      },
    ],
    name: "InvoiceCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
      {
        indexed: false,
        internalType: "address",
        name: "paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "escrowAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint40",
        name: "releaseAt",
        type: "uint40",
      },
    ],
    name: "InvoicePaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "metaInvoiceId",
        type: "uint216",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "totalPrice",
        type: "uint256",
      },
    ],
    name: "MetaInvoiceCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "currency",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "sellerAmount",
        type: "uint256",
      },
    ],
    name: "PaymentReleased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Refunded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newHoldPeriod",
        type: "uint256",
      },
    ],
    name: "UpdateReleaseTime",
    type: "event",
  },
  {
    inputs: [],
    name: "BASIS_POINTS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CANCELED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CREATED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_DECIMAL",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_MINIMUM_INVOICE_PRICE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DISPUTED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DISPUTE_DISMISSED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DISPUTE_RESOLVED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DISPUTE_SETTLED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAID",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REFUNDED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "RELEASED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SEQUENCER_GRACE_PERIOD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "cancelInvoice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    name: "checkUpkeep",
    outputs: [
      { internalType: "bool", name: "upkeepNeeded", type: "bool" },
      { internalType: "bytes", name: "performData", type: "bytes" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_seller", type: "address" },
      { internalType: "address", name: "_buyer", type: "address" },
      { internalType: "uint216", name: "_invoiceId", type: "uint216" },
    ],
    name: "computeSalt",
    outputs: [{ internalType: "bytes32", name: "salt", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "createDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "invoiceId", type: "string" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          {
            internalType: "uint32",
            name: "escrowHoldPeriod",
            type: "uint32",
          },
        ],
        internalType: "struct IAdvancedPaymentProcessor.InvoiceCreationParam[]",
        name: "_param",
        type: "tuple[]",
      },
    ],
    name: "createMetaInvoice",
    outputs: [
      { internalType: "uint216", name: "metaInvoiceId", type: "uint216" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "invoiceId", type: "string" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          {
            internalType: "uint32",
            name: "escrowHoldPeriod",
            type: "uint32",
          },
        ],
        internalType: "struct IAdvancedPaymentProcessor.InvoiceCreationParam",
        name: "_param",
        type: "tuple",
      },
    ],
    name: "createSingleInvoice",
    outputs: [{ internalType: "uint216", name: "invoiceId", type: "uint216" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getForwarder",
    outputs: [
      {
        internalType: "address",
        name: "forwarderAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "getInvoice",
    outputs: [
      {
        components: [
          {
            internalType: "uint216",
            name: "invoiceNonce",
            type: "uint216",
          },
          { internalType: "uint40", name: "paidAt", type: "uint40" },
          { internalType: "uint40", name: "createdAt", type: "uint40" },
          { internalType: "uint40", name: "releaseAt", type: "uint40" },
          { internalType: "uint40", name: "expiresAt", type: "uint40" },
          { internalType: "uint8", name: "state", type: "uint8" },
          {
            internalType: "uint32",
            name: "escrowHoldPeriod",
            type: "uint32",
          },
          {
            internalType: "uint216",
            name: "metaInvoiceId",
            type: "uint216",
          },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "address", name: "escrow", type: "address" },
          {
            internalType: "address",
            name: "paymentToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amountPaid",
            type: "uint256",
          },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "balance", type: "uint256" },
        ],
        internalType: "struct IAdvancedPaymentProcessor.Invoice",
        name: "i",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getItems",
    outputs: [{ internalType: "uint216[]", name: "items", type: "uint216[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint216", name: "_metaInvoiceId", type: "uint216" },
    ],
    name: "getMetaInvoice",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "price", type: "uint256" },
          {
            internalType: "uint216[]",
            name: "subInvoiceIds",
            type: "uint216[]",
          },
        ],
        internalType: "struct IAdvancedPaymentProcessor.MetaInvoice",
        name: "m",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMinimumPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "currentMinimumPrice",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNextInvoiceNonce",
    outputs: [
      {
        internalType: "uint216",
        name: "nextInvoiceNonce",
        type: "uint216",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNextMetaInvoiceNonce",
    outputs: [
      {
        internalType: "uint216",
        name: "nextMetaInvoiceId",
        type: "uint216",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_salt", type: "bytes32" }],
    name: "getPredictedAddress",
    outputs: [
      {
        internalType: "address",
        name: "predictedAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSequencerUptimeFeed",
    outputs: [{ internalType: "address", name: "feed", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_paymentToken", type: "address" },
      { internalType: "uint256", name: "_usdAmount", type: "uint256" },
    ],
    name: "getTokenValueFromUsd",
    outputs: [{ internalType: "uint256", name: "tokenValue", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint216", name: "_invoiceId", type: "uint216" },
      { internalType: "uint8", name: "_resolution", type: "uint8" },
      { internalType: "uint256", name: "_sellerShare", type: "uint256" },
    ],
    name: "handleDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint216", name: "_invoiceId", type: "uint216" },
      { internalType: "address", name: "_paymentToken", type: "address" },
    ],
    name: "payInvoice",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint216", name: "_invoiceId", type: "uint216" },
      { internalType: "address", name: "_paymentToken", type: "address" },
    ],
    name: "payMetaInvoice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "payMetaInvoiceWithValue",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    name: "performUpkeep",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "ppStorage",
    outputs: [
      {
        internalType: "contract IPaymentProcessorStorage",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint216", name: "_invoiceId", type: "uint216" },
      { internalType: "uint256", name: "_refundShare", type: "uint256" },
    ],
    name: "refund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "release",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "resolveDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_forwarderAddress",
        type: "address",
      },
    ],
    name: "setForwarderAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint216", name: "_invoiceId", type: "uint216" },
      { internalType: "uint256", name: "_holdPeriod", type: "uint256" },
    ],
    name: "setInvoiceReleaseTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newMinimumPrice",
        type: "uint256",
      },
    ],
    name: "setMinimumPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_token", type: "address" },
      {
        components: [
          {
            internalType: "address",
            name: "aggregator",
            type: "address",
          },
          { internalType: "uint96", name: "heartbeat", type: "uint96" },
        ],
        internalType: "struct IAdvancedPaymentProcessor.PriceFeedConfig",
        name: "_config",
        type: "tuple",
      },
    ],
    name: "setPriceFeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_sequencerUptimeFeed",
        type: "address",
      },
    ],
    name: "setSequencerUptimeFeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalMetaInvoiceCreated",
    outputs: [
      {
        internalType: "uint216",
        name: "totalMetaInvoices",
        type: "uint216",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalUniqueInvoiceCreated",
    outputs: [
      { internalType: "uint216", name: "totalInvoices", type: "uint216" },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
