export const Notes = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_paymentProcessorStorageAddress",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "ALLOWED",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "NOT_ALLOWED",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createNote",
    inputs: [
      { name: "_invoiceId", type: "uint216", internalType: "uint216" },
      { name: "_author", type: "address", internalType: "address" },
      {
        name: "_encryptedContent",
        type: "bytes",
        internalType: "bytes",
      },
      { name: "_share", type: "bool", internalType: "bool" },
    ],
    outputs: [{ name: "noteId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCurrentVersion",
    inputs: [],
    outputs: [{ name: "v", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getNote",
    inputs: [
      { name: "_invoiceId", type: "uint216", internalType: "uint216" },
      { name: "_noteId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "author", type: "address", internalType: "address" },
      { name: "share", type: "bool", internalType: "bool" },
      { name: "content", type: "bytes", internalType: "bytes" },
      { name: "openedStatus", type: "bool", internalType: "bool" },
      { name: "version", type: "uint8", internalType: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getNoteCount",
    inputs: [{ name: "_invoiceId", type: "uint216", internalType: "uint216" }],
    outputs: [{ name: "totalNotes", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPublicKey",
    inputs: [{ name: "_account", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "publicKey",
        type: "tuple",
        internalType: "struct INotes.PublicKey",
        components: [
          { name: "key", type: "bytes", internalType: "bytes" },
          { name: "version", type: "uint8", internalType: "uint8" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isOpened",
    inputs: [
      { name: "_invoiceId", type: "uint216", internalType: "uint216" },
      { name: "_noteId", type: "uint256", internalType: "uint256" },
      { name: "_user", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "isOpen", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ppStorage",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPaymentProcessorStorage",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setAuthorized",
    inputs: [
      { name: "_user", type: "address", internalType: "address" },
      { name: "_enabled", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOpened",
    inputs: [
      { name: "_invoiceId", type: "uint216", internalType: "uint216" },
      { name: "_account", type: "address", internalType: "address" },
      { name: "_noteId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPublicKey",
    inputs: [{ name: "_publicKey", type: "bytes", internalType: "bytes" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateVersion",
    inputs: [{ name: "_newVersion", type: "uint8", internalType: "uint8" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "NoteCreated",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
      {
        name: "noteId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "author",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "share",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "encryptedContent",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NoteStateChanged",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
      {
        name: "noteId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "opened",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PublicKeySet",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "publicKey",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
      {
        name: "version",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "EmptyContent", inputs: [] },
  { type: "error", name: "InvalidPublicKey", inputs: [] },
  { type: "error", name: "NoteNotFound", inputs: [] },
  { type: "error", name: "PublicKeyAlreadySet", inputs: [] },
  { type: "error", name: "PublicKeyMismatch", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
] as const;
