export const paymentProcessor = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_paymentProcessorStorageAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "_minimumInvoicePrice",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_notesAddress",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptPayment",
    inputs: [{ name: "_invoiceId", type: "uint216", internalType: "uint216" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "calculateFee",
    inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "feeValue", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelInvoice",
    inputs: [{ name: "_invoiceId", type: "uint216", internalType: "uint216" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createInvoice",
    inputs: [
      { name: "_price", type: "uint256", internalType: "uint256" },
      { name: "_holdPeriod", type: "uint32", internalType: "uint32" },
      { name: "_storageRef", type: "bytes", internalType: "bytes" },
      { name: "_share", type: "bool", internalType: "bool" },
    ],
    outputs: [{ name: "invoiceId", type: "uint216", internalType: "uint216" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAutomation",
    inputs: [],
    outputs: [
      {
        name: "automationAddress",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDecisionWindow",
    inputs: [],
    outputs: [
      {
        name: "decisionWindowValue",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getInvoiceData",
    inputs: [{ name: "_invoiceId", type: "uint216", internalType: "uint216" }],
    outputs: [
      {
        name: "i",
        type: "tuple",
        internalType: "struct ISimplePaymentProcessor.Invoice",
        components: [
          {
            name: "invoiceNonce",
            type: "uint216",
            internalType: "uint216",
          },
          { name: "createdAt", type: "uint40", internalType: "uint40" },
          { name: "paidAt", type: "uint40", internalType: "uint40" },
          { name: "releaseAt", type: "uint40", internalType: "uint40" },
          {
            name: "invalidateAt",
            type: "uint40",
            internalType: "uint40",
          },
          { name: "expiresAt", type: "uint40", internalType: "uint40" },
          {
            name: "holdPeriod",
            type: "uint32",
            internalType: "uint32",
          },
          { name: "state", type: "uint8", internalType: "uint8" },
          {
            name: "withdrawalRetries",
            type: "uint8",
            internalType: "uint8",
          },
          { name: "feeRate", type: "uint16", internalType: "uint16" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          { name: "escrow", type: "address", internalType: "address" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "balance", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getItems",
    inputs: [],
    outputs: [{ name: "items", type: "uint216[]", internalType: "uint216[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMinimumInvoiceValue",
    inputs: [],
    outputs: [
      { name: "minimumValue", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getNextInvoiceNonce",
    inputs: [],
    outputs: [
      {
        name: "nextInvoiceNonceValue",
        type: "uint216",
        internalType: "uint216",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasDueTasks",
    inputs: [],
    outputs: [{ name: "dueTasksExist", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pay",
    inputs: [
      { name: "_invoiceId", type: "uint216", internalType: "uint216" },
      { name: "_storageRef", type: "bytes", internalType: "bytes" },
      { name: "_share", type: "bool", internalType: "bool" },
    ],
    outputs: [
      {
        name: "escrowAddress",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "ppStorage",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPaymentProcessorStorage",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "processDueTasks",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refundBuyer",
    inputs: [{ name: "_invoiceId", type: "uint216", internalType: "uint216" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rejectPayment",
    inputs: [{ name: "_invoiceId", type: "uint216", internalType: "uint216" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "release",
    inputs: [{ name: "_invoiceId", type: "uint216", internalType: "uint216" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAutomation",
    inputs: [
      {
        name: "_automationAddress",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setDecisionWindow",
    inputs: [
      {
        name: "_newDecisionWindow",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinimumInvoiceValue",
    inputs: [
      {
        name: "_newMinimumInvoiceValue",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AutomationUpdated",
    inputs: [
      {
        name: "automation",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoiceAccepted",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoiceCanceled",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoiceCreated",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
      {
        name: "invoice",
        type: "tuple",
        indexed: false,
        internalType: "struct ISimplePaymentProcessor.Invoice",
        components: [
          {
            name: "invoiceNonce",
            type: "uint216",
            internalType: "uint216",
          },
          { name: "createdAt", type: "uint40", internalType: "uint40" },
          { name: "paidAt", type: "uint40", internalType: "uint40" },
          { name: "releaseAt", type: "uint40", internalType: "uint40" },
          {
            name: "invalidateAt",
            type: "uint40",
            internalType: "uint40",
          },
          { name: "expiresAt", type: "uint40", internalType: "uint40" },
          {
            name: "holdPeriod",
            type: "uint32",
            internalType: "uint32",
          },
          { name: "state", type: "uint8", internalType: "uint8" },
          {
            name: "withdrawalRetries",
            type: "uint8",
            internalType: "uint8",
          },
          { name: "feeRate", type: "uint16", internalType: "uint16" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          { name: "escrow", type: "address", internalType: "address" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "balance", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoicePaid",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
      {
        name: "buyer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amountPaid",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "expiresAt",
        type: "uint40",
        indexed: false,
        internalType: "uint40",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoiceRefunded",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoiceRejected",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoiceReleased",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
      {
        name: "sellerAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "fee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentBurned",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TransferFailed",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawalRetried",
    inputs: [
      {
        name: "invoiceId",
        type: "uint216",
        indexed: true,
        internalType: "uint216",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "attempt",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AcceptanceWindowExceeded", inputs: [] },
  { type: "error", name: "ContractPaused", inputs: [] },
  { type: "error", name: "DuplicateTask", inputs: [] },
  { type: "error", name: "EscrowWithdrawFailed", inputs: [] },
  { type: "error", name: "HoldPeriodHasNotBeenExceeded", inputs: [] },
  {
    type: "error",
    name: "IncorrectPaymentAmount",
    inputs: [
      { name: "_sent", type: "uint256", internalType: "uint256" },
      { name: "_expected", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "InvalidDecisionWindow", inputs: [] },
  { type: "error", name: "InvalidHeapPosition", inputs: [] },
  {
    type: "error",
    name: "InvalidInvoiceState",
    inputs: [
      {
        name: "_invoiceState",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  { type: "error", name: "InvoiceAlreadyExists", inputs: [] },
  { type: "error", name: "InvoiceIsNoLongerValid", inputs: [] },
  { type: "error", name: "InvoiceNotEligibleForRefund", inputs: [] },
  { type: "error", name: "NotAuthorized", inputs: [] },
  { type: "error", name: "Reentrancy", inputs: [] },
  { type: "error", name: "SellerCannotPayOwnedInvoice", inputs: [] },
  { type: "error", name: "TaskNotFound", inputs: [] },
  { type: "error", name: "ValueIsTooLow", inputs: [] },
] as const;
