export const paymentProcessor = [
  {
    inputs: [
      {
        internalType: "address",
        name: "paymentProcessorStorageAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "initialDefaultHoldPeriod",
        type: "uint256",
      },
      { internalType: "uint256", name: "minimumInvoicePrice", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AcceptanceWindowExceeded", type: "error" },
  { inputs: [], name: "AlreadyInitialized", type: "error" },
  { inputs: [], name: "FeeTooHigh", type: "error" },
  { inputs: [], name: "FeeValueCanNotBeZero", type: "error" },
  { inputs: [], name: "HoldPeriodCanNotBeZero", type: "error" },
  { inputs: [], name: "HoldPeriodHasNotBeenExceeded", type: "error" },
  { inputs: [], name: "HoldPeriodShouldBeGreaterThanPrevious", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "sent", type: "uint256" },
      { internalType: "uint256", name: "expected", type: "uint256" },
    ],
    name: "IncorrectPaymentAmount",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "invoiceState", type: "uint256" },
    ],
    name: "InvalidInvoiceState",
    type: "error",
  },
  { inputs: [], name: "InvoiceAlreadyPaid", type: "error" },
  { inputs: [], name: "InvoiceHasAlreadyBeenReleased", type: "error" },
  { inputs: [], name: "InvoiceHasNotBeenAccepted", type: "error" },
  { inputs: [], name: "InvoiceIsNoLongerValid", type: "error" },
  { inputs: [], name: "InvoiceNotEligibleForRefund", type: "error" },
  { inputs: [], name: "InvoiceNotPaid", type: "error" },
  { inputs: [], name: "InvoicePriceIsTooLow", type: "error" },
  { inputs: [], name: "NewOwnerIsZeroAddress", type: "error" },
  { inputs: [], name: "NoHandoverRequest", type: "error" },
  { inputs: [], name: "ReleaseTimeOverflow", type: "error" },
  { inputs: [], name: "SellerCannotPayOwnedInvoice", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  { inputs: [], name: "ValueIsTooLow", type: "error" },
  { inputs: [], name: "ZeroAddressIsNotAllowed", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceKey",
        type: "bytes32",
      },
    ],
    name: "InvoiceAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceKey",
        type: "bytes32",
      },
    ],
    name: "InvoiceCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceKey",
        type: "bytes32",
      },
      {
        components: [
          { internalType: "uint256", name: "invoiceId", type: "uint256" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "escrow", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "amountPaid", type: "uint256" },
          { internalType: "uint32", name: "createdAt", type: "uint32" },
          { internalType: "uint32", name: "paymentTime", type: "uint32" },
          { internalType: "uint32", name: "releaseAt", type: "uint32" },
          { internalType: "uint32", name: "status", type: "uint32" },
        ],
        indexed: false,
        internalType: "struct ISimplePaymentProcessor.Invoice",
        name: "invoice",
        type: "tuple",
      },
    ],
    name: "InvoiceCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceKey",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amountPaid",
        type: "uint256",
      },
    ],
    name: "InvoicePaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceKey",
        type: "bytes32",
      },
    ],
    name: "InvoiceRefunded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceKey",
        type: "bytes32",
      },
    ],
    name: "InvoiceRejected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceKey",
        type: "bytes32",
      },
    ],
    name: "InvoiceReleased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pendingOwner",
        type: "address",
      },
    ],
    name: "OwnershipHandoverCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pendingOwner",
        type: "address",
      },
    ],
    name: "OwnershipHandoverRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceKey",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "releaseDueTimestamp",
        type: "uint256",
      },
    ],
    name: "UpdateHoldPeriod",
    type: "event",
  },
  {
    inputs: [],
    name: "ACCEPTANCE_WINDOW",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ACCEPTED",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BASIS_POINTS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CANCELLED",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CREATED",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAID",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REFUNDED",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REJECTED",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "RELEASED",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VALID_PERIOD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "calculateFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "invoiceKey", type: "bytes32" }],
    name: "cancelInvoice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "pendingOwner", type: "address" },
    ],
    name: "completeOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "invoicePrice", type: "uint256" },
    ],
    name: "createInvoice",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getDefaultHoldPeriod",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "invoiceKey", type: "bytes32" }],
    name: "getInvoiceData",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "invoiceId", type: "uint256" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "escrow", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "amountPaid", type: "uint256" },
          { internalType: "uint32", name: "createdAt", type: "uint32" },
          { internalType: "uint32", name: "paymentTime", type: "uint32" },
          { internalType: "uint32", name: "releaseAt", type: "uint32" },
          { internalType: "uint32", name: "status", type: "uint32" },
        ],
        internalType: "struct ISimplePaymentProcessor.Invoice",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMinimumInvoiceValue",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNextInvoiceId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "invoiceKey", type: "bytes32" }],
    name: "makeInvoicePayment",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "result", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "pendingOwner", type: "address" },
    ],
    name: "ownershipHandoverExpiresAt",
    outputs: [{ internalType: "uint256", name: "result", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ppStorage",
    outputs: [
      {
        internalType: "contract IPaymentProcessorStorage",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "invoiceKey", type: "bytes32" }],
    name: "refundBuyerAfterWindow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "invoiceKey", type: "bytes32" }],
    name: "releaseInvoice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "requestOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "invoiceKey", type: "bytes32" },
      { internalType: "bool", name: "state", type: "bool" },
    ],
    name: "sellerAction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newDefaultHoldPeriod",
        type: "uint256",
      },
    ],
    name: "setDefaultHoldPeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "invoiceKey", type: "bytes32" },
      { internalType: "uint32", name: "holdPeriod", type: "uint32" },
    ],
    name: "setInvoiceReleaseTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newMinimumInvoiceValue",
        type: "uint256",
      },
    ],
    name: "setMinimumInvoiceValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalInvoiceCreated",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;
