export const paymentProcessor = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_paymentProcessorStorageAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_minimumInvoicePrice",
        type: "uint256",
      },
      { internalType: "address", name: "_notesAddress", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AcceptanceWindowExceeded", type: "error" },
  { inputs: [], name: "DuplicateTask", type: "error" },
  { inputs: [], name: "HoldPeriodHasNotBeenExceeded", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "_sent", type: "uint256" },
      { internalType: "uint256", name: "_expected", type: "uint256" },
    ],
    name: "IncorrectPaymentAmount",
    type: "error",
  },
  { inputs: [], name: "InvalidDecisionWindow", type: "error" },
  { inputs: [], name: "InvalidHeapPosition", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "_invoiceState", type: "uint256" },
    ],
    name: "InvalidInvoiceState",
    type: "error",
  },
  { inputs: [], name: "InvoiceAlreadyExists", type: "error" },
  { inputs: [], name: "InvoiceIsNoLongerValid", type: "error" },
  { inputs: [], name: "InvoiceNotEligibleForRefund", type: "error" },
  { inputs: [], name: "NotAuthorized", type: "error" },
  { inputs: [], name: "SellerCannotPayOwnedInvoice", type: "error" },
  { inputs: [], name: "TaskNotFound", type: "error" },
  { inputs: [], name: "ValueIsTooLow", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
    ],
    name: "InvoiceAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
    ],
    name: "InvoiceCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
      {
        components: [
          {
            internalType: "uint216",
            name: "invoiceNonce",
            type: "uint216",
          },
          { internalType: "uint40", name: "createdAt", type: "uint40" },
          { internalType: "uint40", name: "paidAt", type: "uint40" },
          { internalType: "uint40", name: "releaseAt", type: "uint40" },
          {
            internalType: "uint40",
            name: "invalidateAt",
            type: "uint40",
          },
          { internalType: "uint40", name: "expiresAt", type: "uint40" },
          { internalType: "uint8", name: "state", type: "uint8" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "escrow", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "balance", type: "uint256" },
        ],
        indexed: false,
        internalType: "struct ISimplePaymentProcessor.Invoice",
        name: "invoice",
        type: "tuple",
      },
    ],
    name: "InvoiceCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amountPaid",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint40",
        name: "expiresAt",
        type: "uint40",
      },
    ],
    name: "InvoicePaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
    ],
    name: "InvoiceRefunded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
    ],
    name: "InvoiceRejected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
    ],
    name: "InvoiceReleased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint216",
        name: "invoiceId",
        type: "uint216",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "releaseDueTimestamp",
        type: "uint256",
      },
    ],
    name: "UpdateHoldPeriod",
    type: "event",
  },
  {
    inputs: [],
    name: "ACCEPTED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BASIS_POINTS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CANCELED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CREATED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_SELLER_DECISION_WINDOW",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAID",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REFUNDED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REJECTED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "RELEASED",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "acceptPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
    name: "calculateFee",
    outputs: [{ internalType: "uint256", name: "feeValue", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "cancelInvoice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    name: "checkUpkeep",
    outputs: [
      { internalType: "bool", name: "upkeepNeeded", type: "bool" },
      { internalType: "bytes", name: "performData", type: "bytes" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_price", type: "uint256" },
      { internalType: "bytes", name: "_storageRef", type: "bytes" },
      { internalType: "bool", name: "_share", type: "bool" },
    ],
    name: "createInvoice",
    outputs: [{ internalType: "uint216", name: "invoiceId", type: "uint216" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "decisionWindow",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getForwarder",
    outputs: [
      {
        internalType: "address",
        name: "forwarderAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "getInvoiceData",
    outputs: [
      {
        components: [
          {
            internalType: "uint216",
            name: "invoiceNonce",
            type: "uint216",
          },
          { internalType: "uint40", name: "createdAt", type: "uint40" },
          { internalType: "uint40", name: "paidAt", type: "uint40" },
          { internalType: "uint40", name: "releaseAt", type: "uint40" },
          {
            internalType: "uint40",
            name: "invalidateAt",
            type: "uint40",
          },
          { internalType: "uint40", name: "expiresAt", type: "uint40" },
          { internalType: "uint8", name: "state", type: "uint8" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "escrow", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "balance", type: "uint256" },
        ],
        internalType: "struct ISimplePaymentProcessor.Invoice",
        name: "i",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getItems",
    outputs: [{ internalType: "uint216[]", name: "items", type: "uint216[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMinimumInvoiceValue",
    outputs: [
      { internalType: "uint256", name: "minimumValue", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNextInvoiceNonce",
    outputs: [
      {
        internalType: "uint216",
        name: "nextInvoiceNonceValue",
        type: "uint216",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint216", name: "_invoiceId", type: "uint216" },
      { internalType: "bytes", name: "_storageRef", type: "bytes" },
      { internalType: "bool", name: "_share", type: "bool" },
    ],
    name: "pay",
    outputs: [
      { internalType: "address", name: "escrowAddress", type: "address" },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    name: "performUpkeep",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "ppStorage",
    outputs: [
      {
        internalType: "contract IPaymentProcessorStorage",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "refundBuyer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "rejectPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint216", name: "_invoiceId", type: "uint216" }],
    name: "release",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newDecisionWindow",
        type: "uint256",
      },
    ],
    name: "setDecisionWindow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_forwarderAddress",
        type: "address",
      },
    ],
    name: "setForwarderAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint216", name: "_invoiceId", type: "uint216" },
      { internalType: "uint40", name: "_holdPeriod", type: "uint40" },
    ],
    name: "setInvoiceReleaseTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newMinimumInvoiceValue",
        type: "uint256",
      },
    ],
    name: "setMinimumInvoiceValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
