/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IPaymentProcessorV1 {
  export type InvoiceStruct = {
    creator: AddressLike;
    payer: AddressLike;
    escrow: AddressLike;
    price: BigNumberish;
    amountPaid: BigNumberish;
    createdAt: BigNumberish;
    paymentTime: BigNumberish;
    releaseAt: BigNumberish;
    status: BigNumberish;
  };

  export type InvoiceStructOutput = [
    creator: string,
    payer: string,
    escrow: string,
    price: bigint,
    amountPaid: bigint,
    createdAt: bigint,
    paymentTime: bigint,
    releaseAt: bigint,
    status: bigint
  ] & {
    creator: string;
    payer: string;
    escrow: string;
    price: bigint;
    amountPaid: bigint;
    createdAt: bigint;
    paymentTime: bigint;
    releaseAt: bigint;
    status: bigint;
  };
}

export interface PaymentProcessorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACCEPTANCE_WINDOW"
      | "ACCEPTED"
      | "BASIS_POINTS"
      | "CANCELLED"
      | "CREATED"
      | "PAID"
      | "REFUNDED"
      | "REJECTED"
      | "RELEASED"
      | "VALID_PERIOD"
      | "calculateFee"
      | "cancelInvoice"
      | "cancelOwnershipHandover"
      | "completeOwnershipHandover"
      | "createInvoice"
      | "creatorsAction"
      | "getDefaultHoldPeriod"
      | "getFeeRate"
      | "getFeeReceiver"
      | "getInvoiceData"
      | "getMinimumInvoiceValue"
      | "getNextInvoiceId"
      | "makeInvoicePayment"
      | "owner"
      | "ownershipHandoverExpiresAt"
      | "refundPayerAfterWindow"
      | "releaseInvoice"
      | "renounceOwnership"
      | "requestOwnershipHandover"
      | "setDefaultHoldPeriod"
      | "setFeeRate"
      | "setFeeReceiversAddress"
      | "setInvoiceReleaseTime"
      | "setMinimumInvoiceValue"
      | "totalInvoiceCreated"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InvoiceAccepted"
      | "InvoiceCanceled"
      | "InvoiceCreated"
      | "InvoicePaid"
      | "InvoiceRefunded"
      | "InvoiceRejected"
      | "InvoiceReleased"
      | "OwnershipHandoverCanceled"
      | "OwnershipHandoverRequested"
      | "OwnershipTransferred"
      | "UpdateHoldPeriod"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ACCEPTANCE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ACCEPTED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "CANCELLED", values?: undefined): string;
  encodeFunctionData(functionFragment: "CREATED", values?: undefined): string;
  encodeFunctionData(functionFragment: "PAID", values?: undefined): string;
  encodeFunctionData(functionFragment: "REFUNDED", values?: undefined): string;
  encodeFunctionData(functionFragment: "REJECTED", values?: undefined): string;
  encodeFunctionData(functionFragment: "RELEASED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "VALID_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelInvoice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOwnershipHandover",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeOwnershipHandover",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createInvoice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorsAction",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getDefaultHoldPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInvoiceData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumInvoiceValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNextInvoiceId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "makeInvoicePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownershipHandoverExpiresAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundPayerAfterWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseInvoice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestOwnershipHandover",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultHoldPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeReceiversAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setInvoiceReleaseTime",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumInvoiceValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalInvoiceCreated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ACCEPTANCE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ACCEPTED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "CANCELLED", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "CREATED", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PAID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "REFUNDED", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "REJECTED", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RELEASED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VALID_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOwnershipHandover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeOwnershipHandover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorsAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefaultHoldPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFeeRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvoiceData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumInvoiceValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextInvoiceId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeInvoicePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownershipHandoverExpiresAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundPayerAfterWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestOwnershipHandover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultHoldPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeeRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeReceiversAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInvoiceReleaseTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumInvoiceValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalInvoiceCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace InvoiceAcceptedEvent {
  export type InputTuple = [invoiceId: BigNumberish];
  export type OutputTuple = [invoiceId: bigint];
  export interface OutputObject {
    invoiceId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceCanceledEvent {
  export type InputTuple = [invoiceId: BigNumberish];
  export type OutputTuple = [invoiceId: bigint];
  export interface OutputObject {
    invoiceId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceCreatedEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    creator: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [invoiceId: bigint, creator: string, price: bigint];
  export interface OutputObject {
    invoiceId: bigint;
    creator: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoicePaidEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    payer: AddressLike,
    amountPaid: BigNumberish
  ];
  export type OutputTuple = [
    invoiceId: bigint,
    payer: string,
    amountPaid: bigint
  ];
  export interface OutputObject {
    invoiceId: bigint;
    payer: string;
    amountPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceRefundedEvent {
  export type InputTuple = [invoiceId: BigNumberish];
  export type OutputTuple = [invoiceId: bigint];
  export interface OutputObject {
    invoiceId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceRejectedEvent {
  export type InputTuple = [invoiceId: BigNumberish];
  export type OutputTuple = [invoiceId: bigint];
  export interface OutputObject {
    invoiceId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceReleasedEvent {
  export type InputTuple = [invoiceId: BigNumberish];
  export type OutputTuple = [invoiceId: bigint];
  export interface OutputObject {
    invoiceId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipHandoverCanceledEvent {
  export type InputTuple = [pendingOwner: AddressLike];
  export type OutputTuple = [pendingOwner: string];
  export interface OutputObject {
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipHandoverRequestedEvent {
  export type InputTuple = [pendingOwner: AddressLike];
  export type OutputTuple = [pendingOwner: string];
  export interface OutputObject {
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateHoldPeriodEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    releaseDueTimestamp: BigNumberish
  ];
  export type OutputTuple = [invoiceId: bigint, releaseDueTimestamp: bigint];
  export interface OutputObject {
    invoiceId: bigint;
    releaseDueTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentProcessor extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentProcessor;
  waitForDeployment(): Promise<this>;

  interface: PaymentProcessorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACCEPTANCE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  ACCEPTED: TypedContractMethod<[], [bigint], "view">;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  CANCELLED: TypedContractMethod<[], [bigint], "view">;

  CREATED: TypedContractMethod<[], [bigint], "view">;

  PAID: TypedContractMethod<[], [bigint], "view">;

  REFUNDED: TypedContractMethod<[], [bigint], "view">;

  REJECTED: TypedContractMethod<[], [bigint], "view">;

  RELEASED: TypedContractMethod<[], [bigint], "view">;

  VALID_PERIOD: TypedContractMethod<[], [bigint], "view">;

  calculateFee: TypedContractMethod<[_amount: BigNumberish], [bigint], "view">;

  cancelInvoice: TypedContractMethod<
    [_invoiceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelOwnershipHandover: TypedContractMethod<[], [void], "payable">;

  completeOwnershipHandover: TypedContractMethod<
    [pendingOwner: AddressLike],
    [void],
    "payable"
  >;

  createInvoice: TypedContractMethod<
    [_invoicePrice: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  creatorsAction: TypedContractMethod<
    [_invoiceId: BigNumberish, _state: boolean],
    [void],
    "nonpayable"
  >;

  getDefaultHoldPeriod: TypedContractMethod<[], [bigint], "view">;

  getFeeRate: TypedContractMethod<[], [bigint], "view">;

  getFeeReceiver: TypedContractMethod<[], [string], "view">;

  getInvoiceData: TypedContractMethod<
    [_invoiceId: BigNumberish],
    [IPaymentProcessorV1.InvoiceStructOutput],
    "view"
  >;

  getMinimumInvoiceValue: TypedContractMethod<[], [bigint], "view">;

  getNextInvoiceId: TypedContractMethod<[], [bigint], "view">;

  makeInvoicePayment: TypedContractMethod<
    [_invoiceId: BigNumberish],
    [string],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ownershipHandoverExpiresAt: TypedContractMethod<
    [pendingOwner: AddressLike],
    [bigint],
    "view"
  >;

  refundPayerAfterWindow: TypedContractMethod<
    [_invoiceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseInvoice: TypedContractMethod<
    [_invoiceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "payable">;

  requestOwnershipHandover: TypedContractMethod<[], [void], "payable">;

  setDefaultHoldPeriod: TypedContractMethod<
    [_newDefaultHoldPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeRate: TypedContractMethod<
    [_feeRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeReceiversAddress: TypedContractMethod<
    [_newFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  setInvoiceReleaseTime: TypedContractMethod<
    [_invoiceId: BigNumberish, _holdPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinimumInvoiceValue: TypedContractMethod<
    [_minimumInvoiceValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalInvoiceCreated: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACCEPTANCE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ACCEPTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CANCELLED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CREATED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PAID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFUNDED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REJECTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RELEASED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VALID_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateFee"
  ): TypedContractMethod<[_amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelInvoice"
  ): TypedContractMethod<[_invoiceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelOwnershipHandover"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "completeOwnershipHandover"
  ): TypedContractMethod<[pendingOwner: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "createInvoice"
  ): TypedContractMethod<[_invoicePrice: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "creatorsAction"
  ): TypedContractMethod<
    [_invoiceId: BigNumberish, _state: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDefaultHoldPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFeeReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getInvoiceData"
  ): TypedContractMethod<
    [_invoiceId: BigNumberish],
    [IPaymentProcessorV1.InvoiceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMinimumInvoiceValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNextInvoiceId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "makeInvoicePayment"
  ): TypedContractMethod<[_invoiceId: BigNumberish], [string], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownershipHandoverExpiresAt"
  ): TypedContractMethod<[pendingOwner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "refundPayerAfterWindow"
  ): TypedContractMethod<[_invoiceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseInvoice"
  ): TypedContractMethod<[_invoiceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "requestOwnershipHandover"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "setDefaultHoldPeriod"
  ): TypedContractMethod<
    [_newDefaultHoldPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeRate"
  ): TypedContractMethod<[_feeRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeReceiversAddress"
  ): TypedContractMethod<[_newFeeReceiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setInvoiceReleaseTime"
  ): TypedContractMethod<
    [_invoiceId: BigNumberish, _holdPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinimumInvoiceValue"
  ): TypedContractMethod<
    [_minimumInvoiceValue: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalInvoiceCreated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "payable">;

  getEvent(
    key: "InvoiceAccepted"
  ): TypedContractEvent<
    InvoiceAcceptedEvent.InputTuple,
    InvoiceAcceptedEvent.OutputTuple,
    InvoiceAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceCanceled"
  ): TypedContractEvent<
    InvoiceCanceledEvent.InputTuple,
    InvoiceCanceledEvent.OutputTuple,
    InvoiceCanceledEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceCreated"
  ): TypedContractEvent<
    InvoiceCreatedEvent.InputTuple,
    InvoiceCreatedEvent.OutputTuple,
    InvoiceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "InvoicePaid"
  ): TypedContractEvent<
    InvoicePaidEvent.InputTuple,
    InvoicePaidEvent.OutputTuple,
    InvoicePaidEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceRefunded"
  ): TypedContractEvent<
    InvoiceRefundedEvent.InputTuple,
    InvoiceRefundedEvent.OutputTuple,
    InvoiceRefundedEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceRejected"
  ): TypedContractEvent<
    InvoiceRejectedEvent.InputTuple,
    InvoiceRejectedEvent.OutputTuple,
    InvoiceRejectedEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceReleased"
  ): TypedContractEvent<
    InvoiceReleasedEvent.InputTuple,
    InvoiceReleasedEvent.OutputTuple,
    InvoiceReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipHandoverCanceled"
  ): TypedContractEvent<
    OwnershipHandoverCanceledEvent.InputTuple,
    OwnershipHandoverCanceledEvent.OutputTuple,
    OwnershipHandoverCanceledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipHandoverRequested"
  ): TypedContractEvent<
    OwnershipHandoverRequestedEvent.InputTuple,
    OwnershipHandoverRequestedEvent.OutputTuple,
    OwnershipHandoverRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UpdateHoldPeriod"
  ): TypedContractEvent<
    UpdateHoldPeriodEvent.InputTuple,
    UpdateHoldPeriodEvent.OutputTuple,
    UpdateHoldPeriodEvent.OutputObject
  >;

  filters: {
    "InvoiceAccepted(uint256)": TypedContractEvent<
      InvoiceAcceptedEvent.InputTuple,
      InvoiceAcceptedEvent.OutputTuple,
      InvoiceAcceptedEvent.OutputObject
    >;
    InvoiceAccepted: TypedContractEvent<
      InvoiceAcceptedEvent.InputTuple,
      InvoiceAcceptedEvent.OutputTuple,
      InvoiceAcceptedEvent.OutputObject
    >;

    "InvoiceCanceled(uint256)": TypedContractEvent<
      InvoiceCanceledEvent.InputTuple,
      InvoiceCanceledEvent.OutputTuple,
      InvoiceCanceledEvent.OutputObject
    >;
    InvoiceCanceled: TypedContractEvent<
      InvoiceCanceledEvent.InputTuple,
      InvoiceCanceledEvent.OutputTuple,
      InvoiceCanceledEvent.OutputObject
    >;

    "InvoiceCreated(uint256,address,uint256)": TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;
    InvoiceCreated: TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;

    "InvoicePaid(uint256,address,uint256)": TypedContractEvent<
      InvoicePaidEvent.InputTuple,
      InvoicePaidEvent.OutputTuple,
      InvoicePaidEvent.OutputObject
    >;
    InvoicePaid: TypedContractEvent<
      InvoicePaidEvent.InputTuple,
      InvoicePaidEvent.OutputTuple,
      InvoicePaidEvent.OutputObject
    >;

    "InvoiceRefunded(uint256)": TypedContractEvent<
      InvoiceRefundedEvent.InputTuple,
      InvoiceRefundedEvent.OutputTuple,
      InvoiceRefundedEvent.OutputObject
    >;
    InvoiceRefunded: TypedContractEvent<
      InvoiceRefundedEvent.InputTuple,
      InvoiceRefundedEvent.OutputTuple,
      InvoiceRefundedEvent.OutputObject
    >;

    "InvoiceRejected(uint256)": TypedContractEvent<
      InvoiceRejectedEvent.InputTuple,
      InvoiceRejectedEvent.OutputTuple,
      InvoiceRejectedEvent.OutputObject
    >;
    InvoiceRejected: TypedContractEvent<
      InvoiceRejectedEvent.InputTuple,
      InvoiceRejectedEvent.OutputTuple,
      InvoiceRejectedEvent.OutputObject
    >;

    "InvoiceReleased(uint256)": TypedContractEvent<
      InvoiceReleasedEvent.InputTuple,
      InvoiceReleasedEvent.OutputTuple,
      InvoiceReleasedEvent.OutputObject
    >;
    InvoiceReleased: TypedContractEvent<
      InvoiceReleasedEvent.InputTuple,
      InvoiceReleasedEvent.OutputTuple,
      InvoiceReleasedEvent.OutputObject
    >;

    "OwnershipHandoverCanceled(address)": TypedContractEvent<
      OwnershipHandoverCanceledEvent.InputTuple,
      OwnershipHandoverCanceledEvent.OutputTuple,
      OwnershipHandoverCanceledEvent.OutputObject
    >;
    OwnershipHandoverCanceled: TypedContractEvent<
      OwnershipHandoverCanceledEvent.InputTuple,
      OwnershipHandoverCanceledEvent.OutputTuple,
      OwnershipHandoverCanceledEvent.OutputObject
    >;

    "OwnershipHandoverRequested(address)": TypedContractEvent<
      OwnershipHandoverRequestedEvent.InputTuple,
      OwnershipHandoverRequestedEvent.OutputTuple,
      OwnershipHandoverRequestedEvent.OutputObject
    >;
    OwnershipHandoverRequested: TypedContractEvent<
      OwnershipHandoverRequestedEvent.InputTuple,
      OwnershipHandoverRequestedEvent.OutputTuple,
      OwnershipHandoverRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UpdateHoldPeriod(uint256,uint256)": TypedContractEvent<
      UpdateHoldPeriodEvent.InputTuple,
      UpdateHoldPeriodEvent.OutputTuple,
      UpdateHoldPeriodEvent.OutputObject
    >;
    UpdateHoldPeriod: TypedContractEvent<
      UpdateHoldPeriodEvent.InputTuple,
      UpdateHoldPeriodEvent.OutputTuple,
      UpdateHoldPeriodEvent.OutputObject
    >;
  };
}
